ct_management_account_id    = "xxxxxxxxxxxx"
log_archive_account_id      = "xxxxxxxxxxxx"
audit_account_id            = "xxxxxxxxxxxx"
aft_management_account_id   = "xxxxxxxxxxxx"
ct_home_region              = "us-east-1"
tf_backend_secondary_region = "us-west-2"
github_username             = "xxxxxxxxxxxx"